# -*- coding: utf-8 -*-
"""Elevate_lab_Task_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CbDmD_53n73lviuJS0jH5ETUBH0sPulw

# **🍷 Task 5: Exploratory Data Analysis on Wine Quality Dataset**


---


**Objective:**  
The goal of this task is to perform Exploratory Data Analysis (EDA) on the Wine Quality dataset using Python libraries such as Pandas, Matplotlib, and Seaborn. The objective is to extract statistical patterns, visualize relationships between features, and understand how different chemical properties affect the quality of wine.

**Dataset Overview:**  
The dataset contains physicochemical test results of wine samples along with quality ratings given by wine tasters. Each row represents a wine sample with attributes like acidity, sugar, sulphates, alcohol, and a final quality score ranging from 0 to 10.

**Key Steps in This Notebook:**
1. Data Loading and Preliminary Checks
2. Statistical Summary and Data Cleaning
3. Univariate Analysis (distributions)
4. Bivariate and Multivariate Analysis (correlations & comparisons)
5. Final Summary of Key Insights
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Dataset/WineQT.csv")

df.head()

df.info()

df.describe()

df.duplicated().sum()

df.isnull().sum()

df['quality'].value_counts()

sns.histplot(df['quality'], bins=6, kde=False, color='mediumpurple')
plt.title('Wine Quality Distribution')
plt.xlabel('Quality')
plt.ylabel('Count')
plt.show()

sns.boxplot(x='quality', y='alcohol', data=df, color='mediumpurple')
plt.title('Alcohol Content vs Quality')
plt.show()

sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

sns.pairplot(df[['alcohol', 'sulphates', 'volatile acidity', 'citric acid', 'quality']], hue='quality')
plt.show()

"""## **🧾 Final Observations & Insights**


---


📊 **1. Wine Quality Distribution:**
- Most wines are rated between **5 and 6**, indicating a majority of samples are of average quality.
- Classes are slightly imbalanced, with fewer high- and low-quality wines.

🍷 **2. Key Influencing Factors on Quality:**
- **Alcohol** has a strong **positive correlation** with wine quality (correlation = **0.48**).
- **Volatile acidity** shows a **negative correlation** with quality (correlation = **-0.41**).
- **Sulphates** and **citric acid** also contribute positively to quality, but to a lesser extent.

🧪 **3. Visual Insights:**
- High-quality wines generally have:
  - **Higher alcohol** and **sulphates**
  - **Lower volatile acidity**
- Boxplots and pairplots showed clear separation between wine quality groups based on these features.

📉 **4. Less Influential Features:**
- Features like **residual sugar**, **chlorides**, and **density** had very weak or no correlation with quality.

✅ **Conclusion:**
Alcohol, volatile acidity, and sulphates are the most important features for determining wine quality. These insights can be used to guide feature selection in future predictive models or for quality control in winemaking.

"""